# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_fd.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(889, 501)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(683, 384))
        MainWindow.setMaximumSize(QtCore.QSize(1366, 768))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.topMain = QtWidgets.QFrame(self.centralwidget)
        self.topMain.setGeometry(QtCore.QRect(10, 10, 861, 61))
        self.topMain.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.topMain.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topMain.setLineWidth(0)
        self.topMain.setObjectName("topMain")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topMain)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toggleFrame = QtWidgets.QFrame(self.topMain)
        self.toggleFrame.setMaximumSize(QtCore.QSize(70, 60))
        self.toggleFrame.setToolTipDuration(0)
        self.toggleFrame.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.toggleFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toggleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toggleFrame.setLineWidth(0)
        self.toggleFrame.setObjectName("toggleFrame")
        self.menuButton = QtWidgets.QPushButton(self.toggleFrame)
        self.menuButton.setGeometry(QtCore.QRect(0, 0, 71, 61))
        self.menuButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.menuButton.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(50, 50, 50);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"}")
        self.menuButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/cil-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuButton.setIcon(icon)
        self.menuButton.setIconSize(QtCore.QSize(24, 24))
        self.menuButton.setCheckable(False)
        self.menuButton.setChecked(False)
        self.menuButton.setAutoDefault(False)
        self.menuButton.setDefault(False)
        self.menuButton.setFlat(True)
        self.menuButton.setObjectName("menuButton")
        self.horizontalLayout.addWidget(self.toggleFrame)
        self.topBar = QtWidgets.QFrame(self.topMain)
        self.topBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topBar.setObjectName("topBar")
        self.titleBar = QtWidgets.QFrame(self.topBar)
        self.titleBar.setGeometry(QtCore.QRect(-1, -1, 791, 41))
        self.titleBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.titleBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titleBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleBar.setObjectName("titleBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.titleBar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.iconFrame = QtWidgets.QFrame(self.titleBar)
        self.iconFrame.setMaximumSize(QtCore.QSize(40, 16777215))
        self.iconFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.iconFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.iconFrame.setObjectName("iconFrame")
        self.icon = QtWidgets.QLabel(self.iconFrame)
        self.icon.setGeometry(QtCore.QRect(0, 0, 41, 41))
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("icon/cil-browser.png"))
        self.icon.setAlignment(QtCore.Qt.AlignCenter)
        self.icon.setObjectName("icon")
        self.horizontalLayout_2.addWidget(self.iconFrame)
        self.titleFrame = QtWidgets.QFrame(self.titleBar)
        self.titleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.titleLabel = QtWidgets.QLabel(self.titleFrame)
        self.titleLabel.setGeometry(QtCore.QRect(0, 0, 751, 41))
        self.titleLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Calibri\";")
        self.titleLabel.setObjectName("titleLabel")
        self.titleMenuBar = QtWidgets.QFrame(self.titleFrame)
        self.titleMenuBar.setGeometry(QtCore.QRect(670, -1, 81, 41))
        self.titleMenuBar.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.titleMenuBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleMenuBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleMenuBar.setLineWidth(0)
        self.titleMenuBar.setObjectName("titleMenuBar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.titleMenuBar)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_minimize = QtWidgets.QPushButton(self.titleMenuBar)
        self.btn_minimize.setMinimumSize(QtCore.QSize(43, 43))
        self.btn_minimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/cil-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon1)
        self.btn_minimize.setCheckable(False)
        self.btn_minimize.setChecked(False)
        self.btn_minimize.setFlat(True)
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_5.addWidget(self.btn_minimize)
        self.btn_close = QtWidgets.QPushButton(self.titleMenuBar)
        self.btn_close.setEnabled(True)
        self.btn_close.setMinimumSize(QtCore.QSize(43, 43))
        self.btn_close.setMaximumSize(QtCore.QSize(43, 43))
        self.btn_close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon2)
        self.btn_close.setIconSize(QtCore.QSize(24, 16))
        self.btn_close.setCheckable(False)
        self.btn_close.setChecked(False)
        self.btn_close.setFlat(True)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_5.addWidget(self.btn_close)
        self.horizontalLayout_2.addWidget(self.titleFrame)
        self.pageBar = QtWidgets.QFrame(self.topBar)
        self.pageBar.setGeometry(QtCore.QRect(-1, 39, 791, 21))
        self.pageBar.setStyleSheet("background-color: rgb(60, 60, 60);")
        self.pageBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pageBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pageBar.setObjectName("pageBar")
        self.pageTitle = QtWidgets.QLabel(self.pageBar)
        self.pageTitle.setGeometry(QtCore.QRect(6, 0, 111, 20))
        self.pageTitle.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Calibri\";")
        self.pageTitle.setObjectName("pageTitle")
        self.horizontalLayout.addWidget(self.topBar)
        self.contentMain = QtWidgets.QFrame(self.centralwidget)
        self.contentMain.setGeometry(QtCore.QRect(10, 70, 861, 411))
        self.contentMain.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.contentMain.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentMain.setObjectName("contentMain")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.contentMain)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.menuBar = QtWidgets.QFrame(self.contentMain)
        self.menuBar.setMinimumSize(QtCore.QSize(70, 411))
        self.menuBar.setMaximumSize(QtCore.QSize(70, 411))
        self.menuBar.setStyleSheet("background-color: rgb(40, 40, 40)")
        self.menuBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menuBar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.menuBar.setLineWidth(0)
        self.menuBar.setObjectName("menuBar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.menuBar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.menuFrame = QtWidgets.QFrame(self.menuBar)
        self.menuFrame.setStyleSheet("background-color: rgb(40, 40, 40)")
        self.menuFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuFrame.setLineWidth(0)
        self.menuFrame.setObjectName("menuFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.menuFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menuButtonFrame = QtWidgets.QFrame(self.menuFrame)
        self.menuButtonFrame.setMinimumSize(QtCore.QSize(72, 0))
        self.menuButtonFrame.setMaximumSize(QtCore.QSize(72, 16777215))
        self.menuButtonFrame.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(45, 45, 45);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"}")
        self.menuButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuButtonFrame.setObjectName("menuButtonFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menuButtonFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.statusButton = QtWidgets.QPushButton(self.menuButtonFrame)
        self.statusButton.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.statusButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/013-emotion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.statusButton.setIcon(icon3)
        self.statusButton.setIconSize(QtCore.QSize(40, 40))
        self.statusButton.setCheckable(False)
        self.statusButton.setChecked(False)
        self.statusButton.setFlat(True)
        self.statusButton.setObjectName("statusButton")
        self.verticalLayout.addWidget(self.statusButton)
        self.controlButton = QtWidgets.QPushButton(self.menuButtonFrame)
        self.controlButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/012-control.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.controlButton.setIcon(icon4)
        self.controlButton.setIconSize(QtCore.QSize(40, 40))
        self.controlButton.setCheckable(False)
        self.controlButton.setFlat(True)
        self.controlButton.setObjectName("controlButton")
        self.verticalLayout.addWidget(self.controlButton)
        self.mqttButton = QtWidgets.QPushButton(self.menuButtonFrame)
        self.mqttButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/011-cloud.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mqttButton.setIcon(icon5)
        self.mqttButton.setIconSize(QtCore.QSize(40, 40))
        self.mqttButton.setCheckable(False)
        self.mqttButton.setFlat(True)
        self.mqttButton.setObjectName("mqttButton")
        self.verticalLayout.addWidget(self.mqttButton)
        self.resultButton = QtWidgets.QPushButton(self.menuButtonFrame)
        self.resultButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/002-algorithm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resultButton.setIcon(icon6)
        self.resultButton.setIconSize(QtCore.QSize(40, 40))
        self.resultButton.setCheckable(False)
        self.resultButton.setFlat(True)
        self.resultButton.setObjectName("resultButton")
        self.verticalLayout.addWidget(self.resultButton)
        self.horizontalLayout_4.addWidget(self.menuButtonFrame)
        self.verticalLayout_2.addWidget(self.menuFrame, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_3.addWidget(self.menuBar, 0, QtCore.Qt.AlignTop)
        self.content = QtWidgets.QFrame(self.contentMain)
        self.content.setMinimumSize(QtCore.QSize(791, 411))
        self.content.setMaximumSize(QtCore.QSize(791, 411))
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.Pages = QtWidgets.QStackedWidget(self.content)
        self.Pages.setGeometry(QtCore.QRect(0, 0, 791, 411))
        self.Pages.setLineWidth(0)
        self.Pages.setObjectName("Pages")
        self.status = QtWidgets.QWidget()
        self.status.setObjectName("status")
        self.statusTitle = QtWidgets.QLabel(self.status)
        self.statusTitle.setGeometry(QtCore.QRect(110, 60, 541, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.statusTitle.setFont(font)
        self.statusTitle.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 18pt \"Calibri\";")
        self.statusTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.statusTitle.setObjectName("statusTitle")
        self.statusScreenTitle = QtWidgets.QLabel(self.status)
        self.statusScreenTitle.setGeometry(QtCore.QRect(280, 190, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.statusScreenTitle.setFont(font)
        self.statusScreenTitle.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 15pt \"Calibri Light\";")
        self.statusScreenTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.statusScreenTitle.setObjectName("statusScreenTitle")
        self.statusStat = QtWidgets.QLabel(self.status)
        self.statusStat.setGeometry(QtCore.QRect(270, 250, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.statusStat.setFont(font)
        self.statusStat.setStyleSheet("color: rgb(0, 204, 255);\n"
"font: 15pt \"Calibri\";")
        self.statusStat.setAlignment(QtCore.Qt.AlignCenter)
        self.statusStat.setObjectName("statusStat")
        self.Pages.addWidget(self.status)
        self.control = QtWidgets.QWidget()
        self.control.setObjectName("control")
        self.controlFrame = QtWidgets.QFrame(self.control)
        self.controlFrame.setGeometry(QtCore.QRect(0, 20, 261, 351))
        self.controlFrame.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(45, 45, 45);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"}")
        self.controlFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controlFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controlFrame.setObjectName("controlFrame")
        self.faultDetectionLabel = QtWidgets.QLabel(self.controlFrame)
        self.faultDetectionLabel.setGeometry(QtCore.QRect(10, 0, 161, 21))
        self.faultDetectionLabel.setStyleSheet("font: 12pt \"Calibri\";\n"
"color: rgb(0, 204, 255);")
        self.faultDetectionLabel.setObjectName("faultDetectionLabel")
        self.SVMButton = QtWidgets.QPushButton(self.controlFrame)
        self.SVMButton.setGeometry(QtCore.QRect(60, 281, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.SVMButton.setFont(font)
        self.SVMButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.SVMButton.setAutoFillBackground(False)
        self.SVMButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton:checked {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"}")
        self.SVMButton.setCheckable(False)
        self.SVMButton.setChecked(False)
        self.SVMButton.setFlat(True)
        self.SVMButton.setObjectName("SVMButton")
        self.FDAButton = QtWidgets.QPushButton(self.controlFrame)
        self.FDAButton.setGeometry(QtCore.QRect(60, 301, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.FDAButton.setFont(font)
        self.FDAButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.FDAButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton:checked {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"}")
        self.FDAButton.setCheckable(False)
        self.FDAButton.setFlat(True)
        self.FDAButton.setObjectName("FDAButton")
        self.referenceLine = QtWidgets.QLineEdit(self.controlFrame)
        self.referenceLine.setGeometry(QtCore.QRect(140, 52, 113, 16))
        self.referenceLine.setStyleSheet("border: none;\n"
"color: rgb(0, 203, 255);\n"
"background-color: rgb(60, 60, 60);")
        self.referenceLine.setObjectName("referenceLine")
        self.bufferLine = QtWidgets.QLineEdit(self.controlFrame)
        self.bufferLine.setGeometry(QtCore.QRect(140, 70, 113, 16))
        self.bufferLine.setStyleSheet("border: none;\n"
"color: rgb(0, 203, 255);\n"
"background-color: rgb(60, 60, 60);")
        self.bufferLine.setObjectName("bufferLine")
        self.dataSizeLabel = QtWidgets.QLabel(self.controlFrame)
        self.dataSizeLabel.setGeometry(QtCore.QRect(40, 30, 71, 21))
        self.dataSizeLabel.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(0, 204, 255);")
        self.dataSizeLabel.setObjectName("dataSizeLabel")
        self.referenceSizeLabel = QtWidgets.QLabel(self.controlFrame)
        self.referenceSizeLabel.setGeometry(QtCore.QRect(40, 50, 81, 21))
        self.referenceSizeLabel.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.referenceSizeLabel.setObjectName("referenceSizeLabel")
        self.bufferSizeLabel = QtWidgets.QLabel(self.controlFrame)
        self.bufferSizeLabel.setGeometry(QtCore.QRect(40, 66, 61, 21))
        self.bufferSizeLabel.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.bufferSizeLabel.setObjectName("bufferSizeLabel")
        self.gammaLabel = QtWidgets.QLabel(self.controlFrame)
        self.gammaLabel.setGeometry(QtCore.QRect(40, 151, 61, 21))
        self.gammaLabel.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.gammaLabel.setObjectName("gammaLabel")
        self.gammaLine = QtWidgets.QLineEdit(self.controlFrame)
        self.gammaLine.setGeometry(QtCore.QRect(140, 155, 113, 16))
        self.gammaLine.setStyleSheet("border: none;\n"
"color: rgb(0, 203, 255);\n"
"background-color: rgb(60, 60, 60);")
        self.gammaLine.setObjectName("gammaLine")
        self.featureExtractionLabel = QtWidgets.QLabel(self.controlFrame)
        self.featureExtractionLabel.setGeometry(QtCore.QRect(40, 98, 151, 21))
        self.featureExtractionLabel.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(0, 204, 255);")
        self.featureExtractionLabel.setObjectName("featureExtractionLabel")
        self.kernelLabel = QtWidgets.QLabel(self.controlFrame)
        self.kernelLabel.setGeometry(QtCore.QRect(40, 135, 81, 21))
        self.kernelLabel.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.kernelLabel.setObjectName("kernelLabel")
        self.degreeLabel = QtWidgets.QLabel(self.controlFrame)
        self.degreeLabel.setGeometry(QtCore.QRect(40, 168, 61, 21))
        self.degreeLabel.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.degreeLabel.setObjectName("degreeLabel")
        self.degreeLine = QtWidgets.QLineEdit(self.controlFrame)
        self.degreeLine.setGeometry(QtCore.QRect(140, 173, 113, 16))
        self.degreeLine.setStyleSheet("border: none;\n"
"color: rgb(0, 203, 255);\n"
"background-color: rgb(60, 60, 60);")
        self.degreeLine.setObjectName("degreeLine")
        self.eigLabel = QtWidgets.QLabel(self.controlFrame)
        self.eigLabel.setGeometry(QtCore.QRect(40, 187, 101, 21))
        self.eigLabel.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.eigLabel.setObjectName("eigLabel")
        self.eigLine = QtWidgets.QLineEdit(self.controlFrame)
        self.eigLine.setGeometry(QtCore.QRect(140, 191, 113, 16))
        self.eigLine.setStyleSheet("border: none;\n"
"color: rgb(0, 203, 255);\n"
"background-color: rgb(60, 60, 60);")
        self.eigLine.setObjectName("eigLine")
        self.wcssLine = QtWidgets.QLineEdit(self.controlFrame)
        self.wcssLine.setGeometry(QtCore.QRect(140, 230, 113, 16))
        self.wcssLine.setStyleSheet("border: none;\n"
"color: rgb(0, 203, 255);\n"
"background-color: rgb(60, 60, 60);")
        self.wcssLine.setObjectName("wcssLine")
        self.wcssThresLabel = QtWidgets.QLabel(self.controlFrame)
        self.wcssThresLabel.setGeometry(QtCore.QRect(40, 227, 101, 21))
        self.wcssThresLabel.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.wcssThresLabel.setObjectName("wcssThresLabel")
        self.KPCALabel = QtWidgets.QLabel(self.controlFrame)
        self.KPCALabel.setGeometry(QtCore.QRect(70, 114, 131, 16))
        self.KPCALabel.setStyleSheet("font: 7pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.KPCALabel.setObjectName("KPCALabel")
        self.KMMLabel = QtWidgets.QLabel(self.controlFrame)
        self.KMMLabel.setGeometry(QtCore.QRect(70, 210, 131, 16))
        self.KMMLabel.setStyleSheet("font: 7pt \"Calibri\";\n"
"color: rgb(255, 255, 255);")
        self.KMMLabel.setObjectName("KMMLabel")
        self.classifierLabel = QtWidgets.QLabel(self.controlFrame)
        self.classifierLabel.setGeometry(QtCore.QRect(40, 260, 151, 21))
        self.classifierLabel.setStyleSheet("font: 10pt \"Calibri\";\n"
"color: rgb(0, 204, 255);")
        self.classifierLabel.setObjectName("classifierLabel")
        self.kernelBox = QtWidgets.QComboBox(self.controlFrame)
        self.kernelBox.setGeometry(QtCore.QRect(140, 137, 113, 16))
        self.kernelBox.setAutoFillBackground(False)
        self.kernelBox.setStyleSheet("QComboBox{\n"
"    background-color: rgb(60, 60, 60);\n"
"    font: 8pt \"Calibri\";\n"
"    color: rgb(85, 170, 255);\n"
"    padding-left: 2px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 1px solid rgb(50, 50, 50);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px; \n"
"    border-left-width: 2px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    background-image: url(:/16x16/icons/16x16/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.kernelBox.setFrame(False)
        self.kernelBox.setObjectName("kernelBox")
        self.kernelBox.addItem("")
        self.kernelBox.addItem("")
        self.kernelBox.addItem("")
        self.kernelBox.addItem("")
        self.EmptyFrame = QtWidgets.QFrame(self.control)
        self.EmptyFrame.setGeometry(QtCore.QRect(310, 20, 451, 351))
        self.EmptyFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.EmptyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.EmptyFrame.setObjectName("EmptyFrame")
        self.Pages.addWidget(self.control)
        self.mqtt = QtWidgets.QWidget()
        self.mqtt.setObjectName("mqtt")
        self.connectionFrame = QtWidgets.QFrame(self.mqtt)
        self.connectionFrame.setGeometry(QtCore.QRect(0, 20, 241, 81))
        self.connectionFrame.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(45, 45, 45);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"}")
        self.connectionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.connectionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.connectionFrame.setObjectName("connectionFrame")
        self.MQTTSettingsLabel = QtWidgets.QLabel(self.connectionFrame)
        self.MQTTSettingsLabel.setGeometry(QtCore.QRect(10, 0, 141, 21))
        self.MQTTSettingsLabel.setStyleSheet("font: 12pt \"Calibri\";\n"
"color: rgb(0, 204, 255);")
        self.MQTTSettingsLabel.setObjectName("MQTTSettingsLabel")
        self.portButton = QtWidgets.QPushButton(self.connectionFrame)
        self.portButton.setEnabled(False)
        self.portButton.setGeometry(QtCore.QRect(30, 39, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.portButton.setFont(font)
        self.portButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.portButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.portButton.setCheckable(False)
        self.portButton.setFlat(True)
        self.portButton.setObjectName("portButton")
        self.portLine = QtWidgets.QLineEdit(self.connectionFrame)
        self.portLine.setGeometry(QtCore.QRect(90, 43, 113, 16))
        self.portLine.setStyleSheet("border: none;\n"
"color: rgb(0, 203, 255);\n"
"background-color: rgb(60, 60, 60);")
        self.portLine.setObjectName("portLine")
        self.ipLine = QtWidgets.QLineEdit(self.connectionFrame)
        self.ipLine.setGeometry(QtCore.QRect(90, 24, 113, 16))
        self.ipLine.setStyleSheet("border: none;\n"
"color: rgb(0, 203, 255);\n"
"background-color: rgb(60, 60, 60);")
        self.ipLine.setObjectName("ipLine")
        self.ipButton = QtWidgets.QPushButton(self.connectionFrame)
        self.ipButton.setEnabled(False)
        self.ipButton.setGeometry(QtCore.QRect(30, 21, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.ipButton.setFont(font)
        self.ipButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ipButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.ipButton.setCheckable(False)
        self.ipButton.setFlat(True)
        self.ipButton.setObjectName("ipButton")
        self.featureFrame = QtWidgets.QFrame(self.mqtt)
        self.featureFrame.setGeometry(QtCore.QRect(520, 20, 241, 91))
        self.featureFrame.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(45, 45, 45);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"}")
        self.featureFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.featureFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.featureFrame.setObjectName("featureFrame")
        self.featureLabel = QtWidgets.QLabel(self.featureFrame)
        self.featureLabel.setGeometry(QtCore.QRect(10, 0, 141, 21))
        self.featureLabel.setStyleSheet("font: 12pt \"Calibri\";\n"
"color: rgb(0, 204, 255);")
        self.featureLabel.setObjectName("featureLabel")
        self.featureLine = QtWidgets.QLineEdit(self.featureFrame)
        self.featureLine.setGeometry(QtCore.QRect(140, 31, 61, 16))
        self.featureLine.setStyleSheet("border: none;\n"
"color: rgb(0, 203, 255);\n"
"background-color: rgb(60, 60, 60);")
        self.featureLine.setObjectName("featureLine")
        self.num_featureLabel = QtWidgets.QLabel(self.featureFrame)
        self.num_featureLabel.setGeometry(QtCore.QRect(40, 30, 101, 16))
        self.num_featureLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Calibri\";")
        self.num_featureLabel.setObjectName("num_featureLabel")
        self.connectButton = QtWidgets.QPushButton(self.featureFrame)
        self.connectButton.setGeometry(QtCore.QRect(160, 68, 81, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.connectButton.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.connectButton.setFont(font)
        self.connectButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.connectButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/cil-loop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connectButton.setIcon(icon7)
        self.connectButton.setFlat(True)
        self.connectButton.setObjectName("connectButton")
        self.line = QtWidgets.QFrame(self.mqtt)
        self.line.setGeometry(QtCore.QRect(40, 110, 701, 16))
        self.line.setStyleSheet("color: rgb(74, 126, 187);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.mqttTable = QtWidgets.QTableWidget(self.mqtt)
        self.mqttTable.setEnabled(True)
        self.mqttTable.setGeometry(QtCore.QRect(10, 130, 768, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mqttTable.sizePolicy().hasHeightForWidth())
        self.mqttTable.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.mqttTable.setPalette(palette)
        self.mqttTable.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(60, 60, 60);\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QHeaderView::section{\n"
"    color: rgb(255, 255, 255);\n"
"    Background-color: rgb(39, 44, 54);\n"
"    max-width: 30px;\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::horizontalHeader {\n"
"    background-color: rgb(81, 255, 0);\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid rgb(60, 60, 60);\n"
"    background-color: rgb(51, 121, 205);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }")
        self.mqttTable.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mqttTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.mqttTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.mqttTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.mqttTable.setAlternatingRowColors(False)
        self.mqttTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.mqttTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.mqttTable.setShowGrid(True)
        self.mqttTable.setGridStyle(QtCore.Qt.SolidLine)
        self.mqttTable.setObjectName("mqttTable")
        self.mqttTable.setColumnCount(5)
        self.mqttTable.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        item.setFont(font)
        self.mqttTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mqttTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.mqttTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.mqttTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.mqttTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.mqttTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.mqttTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.mqttTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.mqttTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.mqttTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mqttTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.mqttTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.mqttTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.mqttTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.mqttTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mqttTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.mqttTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.mqttTable.setItem(0, 4, item)
        self.mqttTable.horizontalHeader().setVisible(False)
        self.mqttTable.horizontalHeader().setCascadingSectionResizes(False)
        self.mqttTable.horizontalHeader().setDefaultSectionSize(150)
        self.mqttTable.horizontalHeader().setStretchLastSection(True)
        self.mqttTable.verticalHeader().setVisible(False)
        self.mqttTable.verticalHeader().setCascadingSectionResizes(False)
        self.mqttTable.verticalHeader().setHighlightSections(False)
        self.mqttTable.verticalHeader().setStretchLastSection(True)
        self.Pages.addWidget(self.mqtt)
        self.result = QtWidgets.QWidget()
        self.result.setObjectName("result")
        self.resultsFrame = QtWidgets.QFrame(self.result)
        self.resultsFrame.setGeometry(QtCore.QRect(0, 20, 291, 151))
        self.resultsFrame.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(45, 45, 45);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"}")
        self.resultsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.resultsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.resultsFrame.setObjectName("resultsFrame")
        self.resultLabel = QtWidgets.QLabel(self.resultsFrame)
        self.resultLabel.setGeometry(QtCore.QRect(10, 0, 61, 21))
        self.resultLabel.setStyleSheet("font: 12pt \"Calibri\";\n"
"color: rgb(0, 204, 255);")
        self.resultLabel.setObjectName("resultLabel")
        self.currentBufferLabel = QtWidgets.QPushButton(self.resultsFrame)
        self.currentBufferLabel.setEnabled(False)
        self.currentBufferLabel.setGeometry(QtCore.QRect(10, 88, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.currentBufferLabel.setFont(font)
        self.currentBufferLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.currentBufferLabel.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.currentBufferLabel.setFlat(True)
        self.currentBufferLabel.setObjectName("currentBufferLabel")
        self.samplesLabel = QtWidgets.QPushButton(self.resultsFrame)
        self.samplesLabel.setEnabled(False)
        self.samplesLabel.setGeometry(QtCore.QRect(10, 105, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.samplesLabel.setFont(font)
        self.samplesLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.samplesLabel.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.samplesLabel.setFlat(True)
        self.samplesLabel.setObjectName("samplesLabel")
        self.currentBufferLine = QtWidgets.QLineEdit(self.resultsFrame)
        self.currentBufferLine.setEnabled(False)
        self.currentBufferLine.setGeometry(QtCore.QRect(110, 90, 113, 16))
        self.currentBufferLine.setStyleSheet("border: none;\n"
"color: rgb(0, 203, 255);\n"
"background-color: rgb(60, 60, 60);")
        self.currentBufferLine.setText("")
        self.currentBufferLine.setObjectName("currentBufferLine")
        self.samplesLine = QtWidgets.QLineEdit(self.resultsFrame)
        self.samplesLine.setEnabled(False)
        self.samplesLine.setGeometry(QtCore.QRect(110, 108, 113, 16))
        self.samplesLine.setStyleSheet("border: none;\n"
"color: rgb(0, 203, 255);\n"
"background-color: rgb(60, 60, 60);")
        self.samplesLine.setObjectName("samplesLine")
        self.wcssDiffLine = QtWidgets.QLineEdit(self.resultsFrame)
        self.wcssDiffLine.setEnabled(False)
        self.wcssDiffLine.setGeometry(QtCore.QRect(110, 126, 113, 16))
        self.wcssDiffLine.setStyleSheet("border: none;\n"
"color: rgb(0, 203, 255);\n"
"background-color: rgb(60, 60, 60);")
        self.wcssDiffLine.setObjectName("wcssDiffLine")
        self.wcssDiffLabel = QtWidgets.QPushButton(self.resultsFrame)
        self.wcssDiffLabel.setEnabled(False)
        self.wcssDiffLabel.setGeometry(QtCore.QRect(10, 122, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.wcssDiffLabel.setFont(font)
        self.wcssDiffLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.wcssDiffLabel.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.wcssDiffLabel.setFlat(True)
        self.wcssDiffLabel.setObjectName("wcssDiffLabel")
        self.thresResultsFrame = QtWidgets.QFrame(self.resultsFrame)
        self.thresResultsFrame.setGeometry(QtCore.QRect(10, 20, 281, 51))
        self.thresResultsFrame.setStyleSheet("QCheckBox {\n"
"color: rgb(255,255,255);\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border-radius: 7px;\n"
"    background: rgb(50, 50, 50);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 2px solid rgb(155, 187, 89);\n"
"    border: 2px solid rgb(155, 187, 89);\n"
"}")
        self.thresResultsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.thresResultsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.thresResultsFrame.setObjectName("thresResultsFrame")
        self.referenceCheck = QtWidgets.QCheckBox(self.thresResultsFrame)
        self.referenceCheck.setEnabled(False)
        self.referenceCheck.setGeometry(QtCore.QRect(10, 0, 91, 21))
        self.referenceCheck.setAutoFillBackground(False)
        self.referenceCheck.setStyleSheet("")
        self.referenceCheck.setObjectName("referenceCheck")
        self.bufferCheck = QtWidgets.QCheckBox(self.thresResultsFrame)
        self.bufferCheck.setEnabled(False)
        self.bufferCheck.setGeometry(QtCore.QRect(10, 20, 74, 21))
        self.bufferCheck.setAutoFillBackground(False)
        self.bufferCheck.setStyleSheet("")
        self.bufferCheck.setObjectName("bufferCheck")
        self.classifierCheck = QtWidgets.QCheckBox(self.thresResultsFrame)
        self.classifierCheck.setEnabled(False)
        self.classifierCheck.setGeometry(QtCore.QRect(130, 20, 131, 21))
        self.classifierCheck.setAutoFillBackground(False)
        self.classifierCheck.setStyleSheet("")
        self.classifierCheck.setObjectName("classifierCheck")
        self.wcssCheck = QtWidgets.QCheckBox(self.thresResultsFrame)
        self.wcssCheck.setEnabled(False)
        self.wcssCheck.setGeometry(QtCore.QRect(130, 0, 101, 21))
        self.wcssCheck.setAutoFillBackground(False)
        self.wcssCheck.setStyleSheet("")
        self.wcssCheck.setObjectName("wcssCheck")
        self.thresResultsFrame.raise_()
        self.resultLabel.raise_()
        self.currentBufferLabel.raise_()
        self.samplesLabel.raise_()
        self.currentBufferLine.raise_()
        self.samplesLine.raise_()
        self.wcssDiffLine.raise_()
        self.wcssDiffLabel.raise_()
        self.verticalLayoutWidget = QtWidgets.QWidget(self.result)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(420, 10, 341, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.predLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.predLayout.setContentsMargins(0, 0, 0, 0)
        self.predLayout.setSpacing(0)
        self.predLayout.setObjectName("predLayout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.result)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 200, 341, 191))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.XLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.XLayout.setContentsMargins(0, 0, 0, 0)
        self.XLayout.setSpacing(0)
        self.XLayout.setObjectName("XLayout")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.result)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(420, 200, 341, 191))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.SVMLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.SVMLayout.setContentsMargins(0, 0, 0, 0)
        self.SVMLayout.setSpacing(0)
        self.SVMLayout.setObjectName("SVMLayout")
        self.Legends = QtWidgets.QFrame(self.result)
        self.Legends.setGeometry(QtCore.QRect(250, 100, 112, 94))
        self.Legends.setStyleSheet("QCheckBox {\n"
"color: rgb(255,255,255);\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border-radius: 7px;\n"
"    background: rgb(50, 50, 50);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"}")
        self.Legends.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Legends.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Legends.setObjectName("Legends")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Legends)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.referenceLegend = QtWidgets.QCheckBox(self.Legends)
        self.referenceLegend.setEnabled(False)
        self.referenceLegend.setAutoFillBackground(False)
        self.referenceLegend.setStyleSheet("QCheckBox::indicator:checked {\n"
"    background: 2px solid rgb(135, 206, 250);\n"
"    border: 2px solid rgb(135, 206, 250);\n"
"}")
        self.referenceLegend.setChecked(True)
        self.referenceLegend.setObjectName("referenceLegend")
        self.verticalLayout_3.addWidget(self.referenceLegend)
        self.dataStreamLegend = QtWidgets.QCheckBox(self.Legends)
        self.dataStreamLegend.setEnabled(False)
        self.dataStreamLegend.setAutoFillBackground(False)
        self.dataStreamLegend.setStyleSheet("QCheckBox::indicator:checked {\n"
"    background: 2px solid rgb(240, 230, 140);\n"
"    border: 2px solid rgb(240, 230, 140);\n"
"}")
        self.dataStreamLegend.setChecked(True)
        self.dataStreamLegend.setObjectName("dataStreamLegend")
        self.verticalLayout_3.addWidget(self.dataStreamLegend)
        self.normalLegend = QtWidgets.QCheckBox(self.Legends)
        self.normalLegend.setEnabled(False)
        self.normalLegend.setAutoFillBackground(False)
        self.normalLegend.setStyleSheet("QCheckBox::indicator:checked {\n"
"    background: 2px solid rgb(46, 139, 87);\n"
"    border: 2px solid rgb(46, 139, 87);\n"
"}")
        self.normalLegend.setChecked(True)
        self.normalLegend.setObjectName("normalLegend")
        self.verticalLayout_3.addWidget(self.normalLegend)
        self.faultyLegend = QtWidgets.QCheckBox(self.Legends)
        self.faultyLegend.setEnabled(False)
        self.faultyLegend.setAutoFillBackground(False)
        self.faultyLegend.setStyleSheet("QCheckBox::indicator:checked {\n"
"    background: 2px solid rgb(255, 99, 71);\n"
"    border: 2px solid rgb(255, 99, 71);\n"
"}")
        self.faultyLegend.setCheckable(True)
        self.faultyLegend.setChecked(True)
        self.faultyLegend.setObjectName("faultyLegend")
        self.verticalLayout_3.addWidget(self.faultyLegend)
        self.Pages.addWidget(self.result)
        self.horizontalLayout_3.addWidget(self.content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Pages.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MainWindow", "Fault Detection - Teknik Fisika Universitas Gadjah Mada"))
        self.pageTitle.setText(_translate("MainWindow", "System Status Screen |"))
        self.statusTitle.setText(_translate("MainWindow", "Real Time Fault Detection Using On The Fly Training of \n"
" Support Vector Machines"))
        self.statusScreenTitle.setText(_translate("MainWindow", "Status Screen\n"
"________________"))
        self.statusStat.setText(_translate("MainWindow", "No Connection Established"))
        self.faultDetectionLabel.setText(_translate("MainWindow", "Fault Detection Settings"))
        self.SVMButton.setText(_translate("MainWindow", "Support Vector Machines"))
        self.FDAButton.setText(_translate("MainWindow", "Fisher Discriminant Analysis"))
        self.referenceLine.setText(_translate("MainWindow", "100"))
        self.bufferLine.setText(_translate("MainWindow", "50"))
        self.dataSizeLabel.setText(_translate("MainWindow", "Data Sizes"))
        self.referenceSizeLabel.setText(_translate("MainWindow", "Reference Size"))
        self.bufferSizeLabel.setText(_translate("MainWindow", "Buffer Size"))
        self.gammaLabel.setText(_translate("MainWindow", "Gamma"))
        self.gammaLine.setText(_translate("MainWindow", "0.0085"))
        self.featureExtractionLabel.setText(_translate("MainWindow", "Feature Extraction Settings"))
        self.kernelLabel.setText(_translate("MainWindow", "Kernel"))
        self.degreeLabel.setText(_translate("MainWindow", "Degree"))
        self.degreeLine.setText(_translate("MainWindow", "0"))
        self.eigLabel.setText(_translate("MainWindow", "PCA Eigenvectors"))
        self.eigLine.setText(_translate("MainWindow", "589"))
        self.wcssLine.setText(_translate("MainWindow", "110"))
        self.wcssThresLabel.setText(_translate("MainWindow", "WCSS Threshold"))
        self.KPCALabel.setText(_translate("MainWindow", "Kernel Fisher Discriminant Analysis"))
        self.KMMLabel.setText(_translate("MainWindow", "K-means Clustering"))
        self.classifierLabel.setText(_translate("MainWindow", "Classifier"))
        self.kernelBox.setItemText(0, _translate("MainWindow", "RBF"))
        self.kernelBox.setItemText(1, _translate("MainWindow", "Gaussian"))
        self.kernelBox.setItemText(2, _translate("MainWindow", "Polynomial"))
        self.kernelBox.setItemText(3, _translate("MainWindow", "Linear"))
        self.MQTTSettingsLabel.setText(_translate("MainWindow", "Connection Settings"))
        self.portButton.setText(_translate("MainWindow", "Port"))
        self.portLine.setText(_translate("MainWindow", "1883"))
        self.ipLine.setText(_translate("MainWindow", "127.168.100.42"))
        self.ipButton.setText(_translate("MainWindow", "IP Address"))
        self.featureLabel.setText(_translate("MainWindow", "Feature Information"))
        self.featureLine.setText(_translate("MainWindow", "52"))
        self.num_featureLabel.setText(_translate("MainWindow", "Number of Features"))
        self.connectButton.setText(_translate("MainWindow", "  Connect"))
        self.mqttTable.setSortingEnabled(False)
        item = self.mqttTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.mqttTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.mqttTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.mqttTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.mqttTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.mqttTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.mqttTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.mqttTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.mqttTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.mqttTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Topics"))
        item = self.mqttTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.mqttTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last Received"))
        item = self.mqttTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Messages"))
        item = self.mqttTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Content"))
        __sortingEnabled = self.mqttTable.isSortingEnabled()
        self.mqttTable.setSortingEnabled(False)
        self.mqttTable.setSortingEnabled(__sortingEnabled)
        self.resultLabel.setText(_translate("MainWindow", "Results"))
        self.currentBufferLabel.setText(_translate("MainWindow", "Current Buffer Size"))
        self.samplesLabel.setText(_translate("MainWindow", "Samples Received"))
        self.wcssDiffLabel.setText(_translate("MainWindow", "WCSS Difference"))
        self.referenceCheck.setText(_translate("MainWindow", "Reference Size"))
        self.bufferCheck.setText(_translate("MainWindow", "Buffer Size"))
        self.classifierCheck.setText(_translate("MainWindow", "Classifier Convergent"))
        self.wcssCheck.setText(_translate("MainWindow", "WCSS Threshold"))
        self.referenceLegend.setText(_translate("MainWindow", "Reference"))
        self.dataStreamLegend.setText(_translate("MainWindow", "Data Stream"))
        self.normalLegend.setText(_translate("MainWindow", "Normal"))
        self.faultyLegend.setText(_translate("MainWindow", "Faulty"))
import files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
